const products = [
  {
    id: 2,
    name: "Lenovo IP1 15IGL7 Celeron-N4120/4GB/128GB Laptop",
    description:
      "Το Lenovo IdeaPad 1 ανεβάζει τον πήχη στη κατηγορία του προσιτού laptop, καθώς προσφέρει έναν εξαιρετικά αποδοτικό επεξεργαστή Intel έως και 12ης γενιάς σε ένα λεπτό και συμπαγές πλαίσιο 17,9 χιλιοστών που κάνει το multitasking παιχνιδάκι ενώ ενισχύει την ενεργειακή απόδοση με διάρκεια μπαταρίας έως και 11 ώρες και γρήγορη φόρτιση. Το στενό του πλαίσιο και στις τέσσερις πλευρές προσφέρει μέγιστη αναλογία οθόνης, επίσης διαθέτει ηχεία Dolby Audio και Flip to Start για άμεση εκκίνηση",
    count: 5,
    price: 299.0,
    category: "Computers",
    images: [{ path: "/images/computers-1.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attrs: [{ key: "color", value: "blue" }],
  },
  {
    name: "HP 15s-fq2006nv i3-1115G4/4GB/256GB Laptop",
    description:
      "Διατήρησε την παραγωγικότητά σου και ψυχαγωγήσου από οπουδήποτε χάρη στην μπαταρία μεγάλης διάρκειας. Με λεπτή σχεδίαση micro-edge για να επικεντρώνεσαι σε αυτό που σε ενδιαφέρει.",
    count: 5,
    price: 429,
    category: "Computers",
    images: [{ path: "/images/computers-2.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attrs: [
      { key: "color", value: "black" },
      { key: "RAM", value: "1 TB" },
    ],
  },
  {
    name: "Toshiba Dynabook Satellite Pro C50-J-10K i3/8GB/256GB Laptop",
    description:
      "Κάνε την εργασία σου πιο απλή με το αξιόπιστο Satellite PRO C50. Αυτό το ελαφρύ laptop με οθόνη 15.6” και μεγάλη μπαταρία,είναι σχεδιασμένο για να σε διευκολύνει και να βελτιώνει την παραγωγικότητα σου, προσφέροντας μεγάλη συνδεσιμότητα, γρήγορο Wi-Fi, και όλα τα χαρακτηριστικά απόδοσης και ασφάλειας που χρειάζεσαι ώστε να ολοκληρώνεις με άνεση τις εργασίες σου.",
    count: 5,
    price: 459,
    category: "Computers",
    images: [{ path: "/images/computers-3.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attrs: [
      { key: "color", value: "black" },
      { key: "RAM", value: "1 TB" },
    ],
  },
  {
    name: "Asus Vivobook 15 X1504ZA-BQ531W i5-1235U/16GB/1TB Laptop",
    description:
      "Οι καθημερινές σου εργασίες αποκτούν άλλη αίσθηση με το Vivobook 15, το εργαλείο που θα σου επιτρέψει να κάνεις τα πάντα ευκολότερα όπου κι αν βρίσκεσαι. Προσφέρει μία απόλυτα φιλική και υγιεινή εμπειρία χρήσης με οθόνη που περιστρέφεται κατά 180°, φυσικό κάλυμμα κάμερας και ASUS Antimicrobial Guard Plus που προστατεύει τις επιφάνειες στις οποίες ακουμπάς συχνότερα από βλαβερά βακτήρια. Κάνε τις μέρες σου ομορφότερες με το Vivobook 15!.",
    count: 5,
    price: 759,
    category: "Computers",
    images: [{ path: "/images/computers-4.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attrs: [
      { key: "color", value: "black" },
      { key: "RAM", value: "1 TB" },
    ],
  },
  {
    id: 3,
    name: "Η Ρόζα της Σμύρνης",
    description:
      "Η αινιγματική σμυρνιά αρχόντισσα Ρόζα ζει επί δεκαετίες με το βάρος ενός μυστικού, που κρατά πεισματικά σφραγισμένο ακόμα και από την 28χρονη εγγονή της, Μαριάννα, τον μοναδικό άνθρωπο που έχει στον κόσμο. Ένα μυστικό που έρχεται από την Σμύρνη του 1922. Το συλλεκτικό πάθος του Δημήτρη, ενός αρχιτέκτονα που αναζητεί στα παράλια της Μικράς Ασίας ίχνη από τις χαμένες πατρίδες, μια παλιά φωτογραφία κι ένα νυφικό λερωμένο με αίμα γίνονται αφορμή για να ανασυρθεί, 60 χρόνια μετά, μια ερωτική ιστορία από το παρελθόν, που θα αλλάξει για πάντα τις ζωές της Μαριάννας και του Δημήτρη. H μυρωδιά των παλαιοπωλείων, η πρόκληση του μυστηρίου, η γοητεία του ταξιδιού και η δύναμη του έρωτα συνθέτουν την ατμόσφαιρα και τη διαδρομή που ακολουθούν οι τέσσερις ήρωες στις δυο μεριές του Αιγαίου, συνειδητοποιώντας πως οι μικρές ιστορίες των ανθρώπων είναι αυτές που σφραγίζουν τη μεγάλη Ιστορία.",
    count: 5,
    price: 15,
    category: "Movies",
    images: [{ path: "/images/movies-1.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    id: 4,
    name: "Επικίνδυνη αποστολή: Η Πτώση",
    description:
      "Ο Τομ Κρουζ επιστρέφει και η δράση ξεπερνά κάθε προηγούμενο στην έκτη και πιο επική ταινία του κορυφαίου κινηματογραφικού franchise Σε μια επικίνδυνη αποστολή να ανακτήσει κλεμμένο πλουτώνιο, ο Ίθαν Χαντ (Τομ Κρουζ) επιλέγει να σώσει την ομάδα του παρά να ολοκληρώσει την αποστολή, επιτρέποντας σε πυρηνικά όπλα να πέσουν στα χέρια ενός πολύ επικίνδυνου δικτύου πολύ ικανών πρακτόρων που είναι αποφασισμένοι να καταστρέψουν τον πολιτισμό. Με τον κόσμο να κινδυνεύει τώρα, ο Ίθαν και η ομάδα του (Σάιμον Πεγκ, Βινγκ Ρέιμς, Ρεμπέκα Φέργκιουσον) είναι αναγκασμένοι να συνεργαστούν, παρά τους δισταγμούς τους, με έναν σκληρό πράκτορα της CIA (Χένρι Κάβιλ), ενώ έχουν αντίπαλο τον χρόνο για να σταματήσουν την πυρηνική καταστροφή. Ποτέ άλλοτε μια απειλή δεν ήταν τόσο καταστροφική, επικίνδυνες σκηνές τόσο συγκλονιστικές και μια αποστολή τόσο επικίνδυνη!",
    count: 5,
    price: 20,
    category: "Movies",
    images: [{ path: "/images/movies-2.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
  },

  {
    id: 1,
    name: "Εκδικητές 4: Η Τελευταία Πράξη",
    description:
      "Οι Εκδικητές έχουν ηττηθεί από τον Thanos, που αφού απέκτησε τους έξι Λίθους της Αιωνιότητας, ολοκλήρωσε το διεστραμμένο του σχέδιο και εξαφάνισε τον μισό ανθρώπινο πληθυσμό, συμπεριλαμβανομένων πολλών Εκδικητών. Οι εναπομείναντες Εκδικητές αντιμετωπίζουν την πιο μεγάλη πρόκληση τους μέχρι σήμερα. Πρέπει να βρουν τη δύναμη να νικήσουν τον Thanos μια για πάντα.",
    count: 5,
    price: 21,
    category: "Movies",
    images: [{ path: "/images/movies-3.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    id: 1,
    name: "Ο Χιονάνθρωπος",
    description:
      " Σε παραγωγή του Μάρτιν Σκορτσέζε, η ταινία Ο Χιονάνθρωπος είναι βασισμένη στην bestseller σειρά βιβλίων θρίλερ του Jo Nesbø σύμφωνα με τους New York Times. Ο επικεφαλής μιας ελίτ ομάδας ντετέκτιβ (Μάικλ Φασμπέντερ) ερευνά την εξαφάνιση ενός θύματος που συνέβη με το πρώτο χιόνι του χειμώνα, και φοβάται ότι ένας άπιαστος κατά συρροή δολοφόνος έχει πάλι ενεργοποιηθεί. Με τη βοήθεια μιας ευφυούς νεοσύλλεκτης (Ρεμπέκα Φέργκιουσον), ο αστυνομικός πρέπει να συνδέσει παλιές υποθέσεις πολλών δεκαετιών με την νέα βάναυση επίθεση και ελπίζει ότι θα καταφέρει να νικήσει αυτό το αδιανόητο κακό πριν πέσει το επόμενο χιόνι.",
    count: 5,
    price: 10,
    category: "Movies",
    images: [{ path: "/images/movies-4.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "HP LaserJet HP M209dw Instant Ink Εκτυπωτής Laser",
    description:
      "O μονόχρωμος LaserJet HP M209dw Instant Ink εκτυπωτής laser της HP είναι υψηλής παραγωγικότητας με γρήγορη εκτύπωση διπλής όψης και εφαρμογή HP Smart που σε βοηθά να εξοικονομείς χρόνο. Βασίσου σε πιο αξιόπιστες συνδέσεις, ξένοιαστη εμπειρία εκτύπωσης και την θρυλική ποιότητα HP.",
    count: 5,
    price: 225,
    category: "Printers",
    images: [{ path: "/images/printers-1.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Epson EcoΤank L1250 Εκτυπωτής",
    description:
      "Απόλαυσε ασυναγώνιστο κόστος ανά σελίδα με εξοικονόμηση έως 90% στο κόστος μελανιών με την πρωτοποριακή σειρά EcoTank, η οποία διαθέτει μόνιμη κεφαλή εκτύπωσης χωρίς κρυφά κόστη. Τύπωσε χιλιάδες σελίδες με το σετ μελανιών που συμπεριλαμβάνεται και ισοδυναμεί με 66 cartridges!",
    count: 5,
    price: 199,
    category: "Printers",
    images: [{ path: "/images/printers-2.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Brother MFC-L2710DW Laser Πολυμηχάνημα",
    description:
      "Το MFC-L2710DW είναι ιδανικό για το πολυάσχολο σπίτι και το μικρό γραφείο, που χρειάζονται πολυλειτουργικό εκτυπωτή. Αυτή η απλή στη χρήση και εύκολη στη ρύθμιση συσκευή προσφέρει εκτυπώσεις επαγγελματικής ποιότητας, καθώς και ενσωματωμένη ασύρματη συνδεσιμότητα για εκτύπωση από smatphone και tablet.",
    count: 5,
    price: 229,
    category: "Printers",
    images: [{ path: "/images/printers-3.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Canon Pixma MG2550S Πολυμηχάνημα",
    description:
      "Το πολυμηχάνημα Canon Pixma MG2550S είναι ιδανικό για καθημερινή χρήση και εργασίες εκτύπωσης, σάρωσης και αντιγραφής. Από πυκνογραμμένα έγγραφα μέχρι οικογενειακές φωτογραφίες, ο compact μηχανισμός εκτύπωσης του Canon PIXMA MG2550S έχει σχεδιαστεί με στόχο την ποιότητα και την ευχρηστία.",
    count: 5,
    price: 59,
    category: "Printers",
    images: [{ path: "/images/printers-4.png" }],
    rating: 4,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Microsoft Office 2021 Home & Student 1 PC/Mac Ηλεκτρονική Άδεια",
    description:
      "Το Office 2021 Έκδοση για οικιακή χρήση και μαθητές είναι για σπουδαστές και οικογένειες που θέλουν τις κλασικές εφαρμογές του Office, συμπεριλαμβανομένων των Word, Excel, και PowerPoint για Windows 11 ή 10. Μια εφάπαξ αγορά εγκαθίσταται σε 1 PC ή Mac για χρήση στο σπίτι ή το σχολείο.",
    count: 5,
    price: 149,
    category: "Software",
    images: [{ path: "/images/software-1.png" }],
    rating: 4,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Kaspersky Total Security 1 Device, 2 Years Software",
    description:
      "Περιλαμβάνει προστασία από κακόβουλο λογισμικό, προστασία από παρακολούθηση, προστασία πληρωμών και ασφάλεια για τα παιδιά, τους κωδικούς πρόσβασης και το Wi-Fi.\r\n«Απευθύνεται για Ακαδημαϊκή Χρήση»",
    count: 5,
    price: 99,
    category: "Software",
    images: [{ path: "/images/software-2.png" }],
    rating: 4,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Bitdefender Internet Security 3PC & 1Mobile Security 1Year Software",
    description:
      "Το Bitdefender Internet Security παρέχει την καλύτερη προστασία για τους Windows υπολογιστές χωρίς καμία επιβράδυνση του συστήματος. Σε κρατά ασφαλή από όλους τους τύπους κακόβουλου λογισμικού, συμπεριλαμβανομένων των εξελιγμένων επιθέσεων ransomware.",
    count: 5,
    price: 24,
    category: "Software",
    images: [{ path: "/images/software-3.png" }],
    rating: 4,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Bitdefender Gravity Zone Security​ - 3 έτη Ηλεκτρονική Άδεια",
    description:
      "Τριετής άδεια χρήσης της ενιαίας κονσόλας λογισμικού Bitdefender GravityZone Business Security για 1 χρήστη. Η Bitdefender GravityZone Business Security είναι μια αποτελεσματική λύση ασφάλειας που έχει σχεδιαστεί για την προστασία μικρομεσαίων οργανισμών από γνωστές και άγνωστες απειλές - συμπεριλαμβανομένων phishing, ransomware, exploits και zero-days.",
    count: 5,
    price: 62,
    category: "Software",
    images: [{ path: "/images/software-4.png" }],
    rating: 4,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Acer 3rd Gen 4/32GB Wi-Fi Black Tablet",
    description:
      "Το tablet 10,1 Acer 4/32 (Gen 3) προσφέρει ισχυρό επεξεργαστή MediaTek, 4 GB RAM και οθόνη αφής 10,1 IPS που προσφέρει υπέροχα χρώματα και καλύπτει τις βασικές ανάγκες του μέσου χρήστη. Επιπλέον, η μπαταρία των 6000mAh σε βοηθά να είσαι παραγωγικός...",
    count: 5,
    price: 159,
    category: "Tablets",
    images: [{ path: "/images/tablets-1.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Samsung Galaxy Tab S8 Ultra 8/128GB Wi-Fi Graphite Tablet",
    description:
      "Για εσένα που επιδιώκεις ακατάπαυστα την αριστεία σε όλες τις πτυχές της ζωής σου, το Galaxy Tab S8 Ultra διαθέτει μεγάλη οθόνη 14.6” για απίστευτα ζωντανή εμπειρία προβολής. Το S Pen σου επιτρέπει να οπτικοποιήσεις την φαντασία σου ενώ το Samsung DeX προσθέτει άνεση επιπέδου υπολογιστή στο tablet σου.",
    count: 5,
    price: 799,
    category: "Tablets",
    images: [{ path: "/images/tablets-2.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "Εισαγωγή στην Python για τις Επιστήμες Υπολογιστών και Δεδομένων",
    description:
      "Εκμάθηση Προγραμματισμού με ΑΙ, Μεγάλα Δεδομένα και το Νέφος, 538 βιωματικά, ρεαλιστικά, παραδείγματα ζωντανού κώδικα σε αποσπάσματα και μελέτες περιπτώσεων  471 ασκήσεις και εργασίες,Άμεση ανάδραση με IPython, Τετράδια Jupyter και 557 ασκήσεις Αυτοεξέτασης, Εστιασμένο σε Βιβλιοθήκες: Χρησιμοποιήστε βιβλιοθήκες της Python και της επιστήμης δεδομένων προκειμένου να φέρετε εις πέρας σημαντικές εργασίες με ελάχιστο κώδικα ",
    count: 10,
    price: 50.0,
    category: "Books",
    images: [{ path: "/images/books-1.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "Το Απουσιολόγιο Του Χρόνου",
    description:
      "“Το Απουσιολόγιο του χρόνου” είναι ένα μαγευτικό ταξίδι στην παιδική μας ηλικία. Στο φόντο βρίσκονται τα έρημα σχολεία του Ελληνισμού στην Ελλάδα και στα Βαλκάνια. Στο προσκήνιο είναι οι άνθρωποι: δάσκαλοι, μαθητές, μαστόροι. Οι άνθρωποι μιλούν και τα σχολεία, ερείπια τα περισσότερα από αυτά, ξαναζωντανεύουν. ",
    count: 5,
    price: 25.0,
    category: "Books",
    images: [{ path: "/images/books-2.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "C Προγραμματισμός, 5η Έκδοση",
    description:
      "Η C είναι μία από τις πιο δημοφιλείς γλώσσες προγραμματισμού σε όλο τον κόσμο. Αυτή η νέα έκδοση του πιο δημοφιλούς βιβλίου για τη C παρουσιάζει τέσσερεις από τις πιο δημοφιλείς μεθόδους προγραμματισμού των ημερών μας: διαδικαστικός, αντικειμένων, αντικειμενοστραφής και γενικός προγραμματισμός.Το C Προγραμματισμός, Πέμπτη έκδοση, συνεχίζει μια παράδοση υπεροχής. Το βιβλίο παρουσιάζει τη C με σαφήνεια και ακρίβεια, απευθύνεται σε αρχάριους προγραμματιστές και με έναν καλά οργανωμένο τρόπο αναπτύσσεται από απλές έννοιες ως την απόλυτη περιγραφή του συνόλου της γλώσσας. Γίνεται παρουσίαση όλων των πτυχών της γλώσσας, κάτι που καθιστά το βιβλίο πολύτιμο για έμπειρους προγραμματιστές επίσης. ",
    count: 5,
    price: 57.0,
    category: "Books",
    images: [{ path: "/images/books-3.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "Java Προγραμματισμός, 10η Έκδοση",
    description:
      "Χιλιάδες σπουδαστές και επαγγελματίες έχουν μάθει προγραμματισμό και ανάπτυξη λογισμικού από τα βιβλία, βίντεο, ηλεκτρονικά βιβλία και online κέντρα της Deitel® Το βιβλίο αυτό παρέχει μια σαφή, απλή, ενδιαφέρουσα και διασκεδαστική εισαγωγή στον προγραμματισμό με την Java, χρησιμοποιώντας την προσέγγιση της πρότερης σύνδεσης των αντικειμένων.  ",
    count: 5,
    price: 48.0,
    category: "Books",
    images: [{ path: "/images/books-4.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "Sony DSCH300 Black ",
    description:
      "Φωτογραφική μηχανή DSCH300 με οπτικό ζουμ 35x, αισθητήρα 20,1MP, βίντεο HD και δημιουργικές λειτουργίες, πετυχαίνετε λεπτομερείς εικόνες και βίντεο, ενώ το σώμα τύπου DSLR προσφέρει άνετο χειρισμό.Βγάλτε φωτογραφίες γεμάτες λεπτομέρεια, χάρη στον αισθητήρα υψηλής ανάλυσης Super HAD CCD™ 20,1MP. Αιχμαλωτίστε εικόνες με ζωντανό χρώμα και καθαρότητα, ακόμα και σε μεγέθυνση A4 και πλέον.",
    count: 10,
    price: 197,
    category: "Cameras",
    images: [{ path: "/images/camera-1.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "Sony DSCRX10 Black ",
    description:
      "Φωτογραφική μηχανή DSCRX10 με φακό ZEISS 20x με διάφραγμα F2.8 σε ολόκληρο το εύρος ζουμ και 20,2 MP αισθητήρα Exmor R με οπίσθιο φωτισμό. ",
    count: 6,
    price: 899,
    category: "Cameras",
    images: [{ path: "/images/camera-2.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "Sony ILCE6000L Black ",
    description:
      "Φωτογραφική μηχανή ILCE6000L χωρίς καθρέφτη με αισθητήρα 24,3 MP Exmor APS HD CMOS, επεξεργαστής BIONZ και βίντεο Full HD. Άψογη λήψη, την κατάλληλη στιγμή Λήψεις σε 0,06 δευτερόλεπτα με ταχύτατη αυτόματη εστίαση. Σε αντίθεση με άλλα ανταγωνιστικά μοντέλα, η γρήγορη υβριδική αυτόματη εστίαση της α6000 συνδυάζει τα πλεονεκτήματα της αυτόματης εστίασης με εντοπισμό φάσης και εντοπισμό αντίθεσης.",
    count: 6,
    price: 479,
    category: "Cameras",
    images: [{ path: "/images/camera-3.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "Sony DSCRX100M3 Compact ",
    description:
      "Φωτογραφική μηχανή DSCRX100M3 με αισθητήρα CMOS 20.1 MP, καταπληκτικό οπτικό ζουμ 40x, ηλεκτρονικό εικονοσκόπιο και μικρές διαστάσεις, είναι σχεδιασμένη για τους λάτρεις της φωτογραφίας που βρίσκονται συχνά εν κινήσει. Το ενσωματωμένο ηλεκτρονικό οφθαλμοσκόπιο προσφέρει πιο ακριβή σύνθεση φωτογραφιών, ιδίως σε συνθήκες έντονου φωτισμού. Ένας αισθητήρας ματιού επιτρέπει την άμεση εναλλαγή μεταξύ του οφθαλμοσκοπίου και της οθόνης LCD, για άνετες και εύκολες λήψεις.",
    count: 6,
    price: 479,
    category: "Cameras",
    images: [{ path: "/images/camera-3.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "Canon EOS 5D Mark IV EF-24-105IS f/4 L II USM DSLR ",
    description:
      "Σχεδιασμένη για υψηλή απόδοση σε κάθε περίσταση, η EOS 5D Mark IV είναι μια ολοκληρωμένη και εντυπωσιακή μηχανή, εξαιρετικής κατασκευής. Διαθέτει προηγμένες δυνατότητες εστίασης και φωτομέτρησης, που επιτρέπουν την παρακολούθηση και την αποτύπωση κάθε στιγμής καθώς συμβαίνει, ακόμη και σε δύσκολες συνθήκες φωτισμού.",
    count: 1,
    price: 999,
    category: "Cameras",
    images: [{ path: "/images/camera-5.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "Samsung Galaxy Tab S9 FE 6/128GB Wi-Fi Gray Tablet",
    description:
      "Κάνε αυτό που αγαπάς όπου και όποτε θέλεις! Το Galaxy Tab S9 FE διαθέτει ισχυρό Exynos 1380 chipset για να ενισχύει την παραγωγικότητα σου, και είναι πανεύκολο στη μεταφορά. Απόλαυσε κινηματογραφική ποιότητα θέασης χάρη στην μεγάλη οθόνη 10.9” και τα δύο ηχεία AKG. Αξιοποίησε το παρεχόμενο S Pen για να απογειώσεις την δημιουργικότητα σου όπου και αν βρίσκεσαι.",
    count: 15,
    price: 549,
    category: "Tablets",
    images: [{ path: "/images/tablets-4.png" }],
    rating: 4,
    reviewsNumber: 7,
    reviews: [],
  },
  {
    name: "Lenovo P11 Plus 6GB/128GB Wifi & Precision Pen 2 & Keyboard Tablet",
    description:
      "Εξασφάλισε εμπειρία πρώτης κατηγορίας μέσω των εντυπωσιακών 2K γραφικών του Lenovo Tab P11 Plus στην οθόνη 11 ιντσών, με τα τετραπλά ηχεία με στερεοφωνικό σύστημα που συντονίζεται από το Dolby Atmos και τεράστια διάρκεια ζωής μπαταρίας, με πολύ λεπτό σώμα από κράμα αλουμινίου με σύγχρονο διπλό φινίρισμα. Στην συσκευασία συμπεριλαμβάνονται pen και πληκτρολόγιο ελληνικό.",
    count: 4,
    price: 399,
    category: "Tablets",
    images: [{ path: "/images/tablets-3.png" }],
    rating: 4,
    reviewsNumber: 8,
    reviews: [],
  },
  {
    name: "Kiddoboo 8 Wi-Fi Yellow Tablet",
    description:
      "Παιδικό tablet Kiddoboo το οποίο διαθέτει ελαφρύ και λεπτό σχεδιασμό, οθόνη 8” IPS LCD με ανάλυση 1280 x 800 pixels που προσφέρει ζωντανά χρώματα για να απολαμβάνεις εσύ και το παιδι σου ξεκούραστα τα παιχνίδια & τις εκπαιδευτικές εφαρμογές. Είναι εξοπλισμένο με 2GB μνήμη RAM και 32GB αποθηκευτικού χώρου και με τετραπύρηνο επεξεργαστή χρονισμένο στα 1.3Ghz. Η μπαταρία των 5.000mAh προσφέρει μεγάλη αυτονομία για να το έχεις πάντα μαζί.",
    count: 25,
    price: 99,
    category: "Tablets",
    images: [{ path: "/images/tablets-5.png" }],
    rating: 3,
    reviewsNumber: 9,
    reviews: [],
  },
  {
    name: "LG 43UR81006 43 Τηλεόραση Smart 4K TV",
    description:
      "Καθηλωτική Real 4K UHD ανάλυση με 4K HDR10 Pro για να απολαμβάνεις το αγαπημένο σου περιεχόμενο στο έπακρο με εντυπωσιακή λεπτομέρεια και ζωηρά χρώματα. Ο επεξεργαστής α5 ΑΙ 4K Gen6 και οι έξυπνες λειτουργίες όπως ThinQ AI και WebOS αναβαθμίζουν το περιεχόμενο σου για να σου προσφέρουν μια πιο έξυπνη εμπειρία θέασης. Επωφελήσου από το ενσωματωμένο streaming, συμπεριλαμβανομένων των Netflix, Apple TV+ και Disney+ για ατέλειωτες ώρες ψυχαγωγίας.",
    count: 5,
    price: 429,
    category: "Monitors",
    images: [{ path: "/images/monitors-1.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Samsung Crystal UHD UE75CU7172 75'' Τηλεόραση Smart 4K TV",
    description:
      "Η Crystal UHD τηλεόραση Samsung  CU7000 συνδυάζει Crystal Processor 4K για να νιώθεις κάθε απόχρωση σε ισχυρή ανάλυση 4K, Smart Hub για να ανακαλύπτεις το αγαπημένο σου περιεχόμενο σε ένα μέρος, PurColor που δίνει εντυπωσιακό χρώμα για ζωντανή, ρεαλιστική εικόνα και SmartThings έξυπνη εφαρμογή για το σπίτι σου.",
    count: 10,
    price: 799,
    category: "Monitors",
    images: [{ path: "/images/monitors-2.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "TCL 40S6200 40'' Τηλεόραση Smart TV",
    description:
      "Η σειρά TCL S62 συνδυάζει την μοντέρνα σχεδίαση χωρίς πλαίσιο, την ποιότητα εικόνας HDR και το πιο προηγμένο σύστημα Android TV. Παρακολούθησε ταινίες blockbuster με πλούσιο ήχο Dolby Audio, μετάδωσε εφαρμογές και απόλαυσε παιχνίδια για πολλούς παίκτες. Και με τον ενσωματωμένο Βοηθό Google, μπορείς να κάνεις περισσότερα και πιο γρήγορα. ",
    count: 3,
    price: 189,
    category: "Monitors",
    images: [{ path: "/images/monitors-3.png" }],
    rating: 4,
    reviewsNumber: 7,
    reviews: [],
  },
  {
    name: "TCL LED 32S5200 32 Τηλεόραση Smart TV",
    description:
      "Η σειρά TCL S52 συνδυάζει τη λεπτή, σύγχρονη σχεδίαση, την ποιότητα εικόνας HDR και το πιο προηγμένο σύστημα Smart TV: Android TV. Σχεδιασμένη για όσους δεν θέλουν να συμβιβαστούν μεταξύ της κομψότητας, της ποιότητας εικόνας και της εύκολης πρόσβασης στο περιεχόμενο που αγαπούν, η σειρά TCL S52 επιτρέπει σε όλα τα μέλη της οικογένειάς σου να απολαύσουν το αγαπημένο τους περιεχόμενο.",
    count: 20,
    price: 159,
    category: "Monitors",
    images: [{ path: "/images/monitors-4.png" }],
    rating: 4,
    reviewsNumber: 8,
    reviews: [],
  },
  {
    name: "Sony LED KD55X81K 55'' Τηλεόραση Smart 4K TV",
    description:
      "Απόλαυσε εικόνα και ήχο ανώτατης ποιότητας χάρη στο Triluminos Pro, τον επεξεργαστή 4K HDR Processor X1 και Dolby Vision που βελτιστοποιεί την εικόνα και σου προσφέρει καθηλωτικό ήχο για να απολαμβάνεις στο έπακρο το αγαπημένο σου περιεχόμενο.",
    count: 25,
    price: 699,
    category: "Monitors",
    images: [{ path: "/images/monitors-5.png" }],
    rating: 3,
    reviewsNumber: 9,
    reviews: [],
  },
  {
    name: "Sony PS5 Κονσόλα & Marvels Spider-Man: Miles Morales & Destruction AllStars PS5 Game",
    description:
      "Σετ το οποίο αποτελείται από την κονσόλα PS5 και από τα PS5 Games, Marvel`s Spider-Man: Miles Morales και Destruction AllStars..",
    count: 5,
    price: 629,
    category: "Games",
    images: [{ path: "/images/games-1.png" }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: "Microsoft Xbox Series S Κονσόλα",
    description:
      "Η επόμενη γενιά παιχνιδιού φέρνει τη μεγαλύτερη ψηφιακή βιβλιοθήκη κυκλοφοριών στο μικρότερο Xbox που έγινε ποτέ. Με πιο δυναμικούς κόσμους, ταχύτερους χρόνους φόρτωσης και την προσθήκη του Xbox Game Pass (πωλείται ξεχωριστά), η πλήρως ψηφιακή κονσόλα Xbox Series S είναι ό,τι καλύτερο για παιχνίδια.",
    count: 10,
    price: 309,
    category: "Games",
    images: [{ path: "/images/games-2.png" }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: "Nintendo Switch Grey 2019 Κονσόλα",
    description:
      "Το Nintendo Switch, προσφέρει εξαιρετική gaming εμπειρία τόσο στο σπίτι, όσο και έξω από αυτό! Σήκω από τον καναπέ σου και ένωσε, το διασπώμενο χειριστήριο με την κονσόλα, η οποία διαθέτει ενσωματωμένη οθόνη υψηλής ανάλυσης, για να συνεχίσεις το παιχνίδι σου, οπουδήποτε εσύ θες, ακριβώς από το σημείο που το άφησες! Αυτό το μοντέλο προσφέρει διάρκεια ζωής της μπαταρίας από 4.5 έως και 9 ώρες ανάλογα με τη χρήση.",
    count: 15,
    price: 329,
    category: "Games",
    images: [{ path: "/images/games-3.png" }],
    rating: 4,
    reviewsNumber: 7,
    reviews: [],
  },
  {
    name: "Nintendo Switch Lite Turquoise & Animal Crossing: New Horizons Κονσόλα",
    description:
      "Το Nintendo Switch Lite εντάσσεται στην οικογένεια συσκευών της Nintendo και εστιάζει αποκλειστικά στη φορητή εμπειρία, ώστε να σε ακολουθεί όπου και αν πας. Το πακέτο αυτό περιλαμβάνει την κονσόλα Nintendo Switch Lite (Turquoise), download code για το παιχνίδι Animal Crossing: New Horizons και μια συνδρομή 3 μηνών για το Nintendo Switch Online.",
    count: 20,
    price: 259,
    category: "Games",
    images: [{ path: "/images/games-4.png" }],
    rating: 4,
    reviewsNumber: 8,
    reviews: [],
  },
  {
    name: "Microsoft Xbox Series X & Diablo IV (Voucher Code) & Call Of Duty: Modern Warfare 3 Set",
    description:
      "Λάβε μέρος στην ατελείωτη μάχη μεταξύ των High Heavens και των Burning Hells με το Xbox Series X – Diablo IV Bundle. Περιλαμβάνει το Diablo IV και μπόνους αντικείμενα εντός του παιχνιδιού. Μάζι απόκτησε και το Call Of Duty: Modern Warfare 3.",
    count: 25,
    price: 519,
    category: "Games",
    images: [{ path: "/images/games-5.png" }],
    rating: 3,
    reviewsNumber: 9,
    reviews: [],
  },
];

module.exports = products;
